### ISSUE TITLE
git cherry-pick not working like I thought

### ISSUE THREAD

**Issue by anton-seaice** [COSIMA/MOM6-CICE6#27]
I tried to cherry-pick two commits from the RYF branch to IAF branch - but ended up with new commits:

51d97ab5a5ceafbb75fd0e519ab89458654e1ef5
618d3add34e6fcd4064ab58f768b979fd11a9527

but they should be these commits from the ryf branch:

efa43a9761a2586f8f757f99d16c905d1a029740
c45fb289997d82a719b4edc44ab9f2edd729d16e

I obviously don't understand something about how cherry-pick works!

I think we want all commits from ryf to be in the iaf branch i.e. https://github.com/COSIMA/MOM6-CICE6/compare/1deg_jra55do_iaf...1deg_jra55do_ryf compare should have no changes.

We can presumably fix this - but it would re-write the history in the iaf branch ... which I guess means everyone will need to reset their local copies?

@micaeljtoliveira - Help!?

**Comment by micaeljtoliveira** [comment]
@anton-seaice Cherry-pick reapplies a commit on top a new commit. You therefore always end up with a different commit, that is, a commit with a different hash, because it will have a different parent commit. Looking at the commits you mention, they look fine to me, as they seem to apply exactly the same changes to the parent commit.

Does this help?

**Comment by anton-seaice** [comment]
Ah - so there haven't been any other commits applied to both branches since the IAF branch was forked ?

i.e. all the commits in both branches before October 16 are the same (e.g. same hash) but is this because this was before the branches forked? And commits after the branches forked, even if they are the same changes, will have different hashes because they are applied to different parents ?

**Comment by micaeljtoliveira** [comment]
> all the commits in both branches before October 16 are the same (e.g. same hash) but is this because this was before the branches forked?  

Yes, exactly.

> And commits after the branches forked, even if they are the same changes, will have different hashes because they are applied to different parents ?

Yes, and  the reason why they have a different parent is because at some point a given commit was added to one branch but not to the other, that is the branches **diverged**.

**Comment by anton-seaice** [comment]
Ok. This is going to get much messier than I thought!

**Comment by aekiss** [comment]
If there are lots of fiddly unsquashed commits, would it be easier to edit by hand (eg copying altered files between branches and tweaking as needed, based on git diffs between branches) rather than using cherry-pick?

**Comment by anton-seaice** [comment]
> If there are lots of fiddly unsquashed commits, would it be easier to edit by hand (eg copying altered files between branches and tweaking as needed, based on git diffs between branches) rather than using cherry-pick?

This sounds like squashing the commits ? :)

**Comment by aekiss** [comment]
Yes, but it might be easier to just compare the heads of the branches and make the necessary changes manually rather than working out which commits would need to be cherry-picked (then possibly tweaked) to get the same result?

I guess it depends on how many commits there are and how cleanly they can be reapplied in the other branch.

**Comment by anton-seaice** [comment]
> Yes, but it might be easier to just compare the heads of the branches and make the necessary changes manually rather than working out which commits would need to be cherry-picked (then possibly tweaked) to get the same result?
> 
> I guess it depends on how many commits there are and how cleanly they can be reapplied in the other branch.

Oh yes - you could merge with --no-commit and then pick through the changes using something like the vscode source control tool. The nice thing with cherry pick is it links to the original PR.

**Comment by micaeljtoliveira** [comment]
> If there are lots of fiddly unsquashed commits, would it be easier to edit by hand (eg copying altered files between branches and tweaking as needed, based on git diffs between branches) rather than using cherry-pick?

I would only use that option as last resort, because it's easy to miss a conflict (lines changed in both branches) when doing things manually. On the other hand, git will always tell you when there's a conflict, be it during a merge, a rebase or a cherry-pick.

> you could merge with --no-commit and then pick through the changes

It actually doesn't change the process much, because in practice  you'll have the same conflicts to resolve.

**Comment by micaeljtoliveira** [comment]
> Ok. This is going to get much messier than I thought!

That's why having a "clean" and logical commit history is important ;)

**Comment by anton-seaice** [comment]
> 
> > you could merge with --no-commit and then pick through the changes
> 
> It actually doesn't change the process much, because in practice you'll have the same conflicts to resolve.

Yes I tried it yesterday and it was messy!

**Comment by micaeljtoliveira** [comment]
I guess we can now close this issue. Just reopen if needed.
